"""
Demo page backend — real OpenAI streaming for test-case & script generation,
plus Playwright execution with live results.
Nothing is stored in the database.
"""

import asyncio
import base64
import json

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from app.api.dependencies import AppContainer, get_container
from .demo_content import DEMO_SCRIPT_TEXT, DEMO_ACCEPTANCE_CRITERIA

router = APIRouter(prefix="/demo", tags=["Demo"])


# ── Prompts ────────────────────────────────────────────────────────────────────

_TC_SYSTEM = (
    "You are a senior QA engineer generating structured test cases with detailed "
    "test steps for Amazon.com shopping flows. Write in clean Markdown."
)

_TC_PROMPT = """Generate a comprehensive test suite for Amazon.com based on the following acceptance criteria.

**Application Under Test:** Amazon.com (https://www.amazon.com)
**Search Queries:** "wireless mouse", "usb keyboard", "laptop stand"

**Acceptance Criteria:**
{criteria}

**Requirements:**
1. Generate exactly 16 test cases total across all criteria.
2. For each test case include:
   - ID (TC-001 through TC-016)
   - Title
   - Type (Positive / Negative)
   - Priority (P0-Critical, P1-High, P2-Medium)
   - Category
   - Preconditions
   - Detailed numbered test steps (3-6 steps each)
   - Expected result for each step
3. 14 test cases should be positive (expected to pass) covering:
   - Homepage load & nav bar verification
   - Searching for multiple products (wireless mouse, usb keyboard, laptop stand)
   - Verifying product cards (title, price, ratings, images)
   - Sorting results by price
   - Search relevance verification
   - Navigating to cart page
   - Product image thumbnails
4. 2 test cases should be negative edge cases (expected to fail), at positions TC-009 and TC-014:
   - TC-009: Voice Search button (not available on desktop web)
   - TC-014: Try Before You Buy (only for clothing)
5. Include a summary table at the end showing all 16 test cases with expected pass/fail status.
6. Format everything in clean Markdown with headers, tables, and proper formatting.
"""

_SCRIPT_SYSTEM = (
    "You are an expert Playwright automation engineer. Generate production-quality "
    "async Python Playwright test scripts for Amazon.com."
)

_SCRIPT_PROMPT = """Generate a complete Playwright async Python test script for Amazon.com based on these test cases:

{test_cases_summary}

**Requirements:**
1. Use `playwright.async_api` with `async_playwright`.
2. Launch Chromium with `headless=False` and `slow_mo=1000`.
3. Use viewport 1280x800, locale="en-US".
4. Set default timeout to 12000ms.
5. Implement all 16 test cases as individual try/except blocks.
6. Use robust Amazon selectors:
   - Search box: `#twotabsearchtextbox`
   - Search button: `#nav-search-submit-button`
   - Search results: `[data-component-type='s-search-result']`
   - Cart: `#nav-cart`, badge: `#nav-cart-count`
7. 2 test cases should intentionally fail (TC-009, TC-014).
8. Print checkmark PASSED or X FAILED for each test case.
9. Print a summary at the end with total passed/failed counts.
10. Include proper error handling and a clean asyncio.run() entry point.
11. Output ONLY the Python code, no markdown fences, no explanation.
"""


# ── GET /demo/info ─────────────────────────────────────────────────────────────

@router.get("/info")
async def demo_info():
    """Return the acceptance criteria and metadata used by the demo."""
    return {
        "acceptance_criteria": DEMO_ACCEPTANCE_CRITERIA,
        "application": "Amazon.com",
        "url": "https://www.amazon.com",
        "search_terms": ["wireless mouse", "usb keyboard", "laptop stand"],
        "total_test_cases": 16,
        "expected_pass": 14,
        "expected_fail": 2,
    }


# ── POST /demo/generate-test-cases/stream ─────────────────────────────────────

@router.post("/generate-test-cases/stream")
async def generate_test_cases_stream(
    container: AppContainer = Depends(get_container),
):
    """Stream test cases + test steps generated by OpenAI in real time."""
    openai_client = container.get_openai_client()
    criteria_text = "\n".join(
        f"{i}. {c}" for i, c in enumerate(DEMO_ACCEPTANCE_CRITERIA, 1)
    )
    prompt = _TC_PROMPT.format(criteria=criteria_text)

    async def event_stream():
        full_text: list[str] = []
        try:
            async for token in openai_client.generate_stream(
                prompt=prompt,
                system=_TC_SYSTEM,
                temperature=0.4,
            ):
                full_text.append(token)
                yield f"data: {json.dumps({'type': 'token', 'token': token})}\n\n"
            yield f"data: {json.dumps({'type': 'done', 'text': ''.join(full_text)})}\n\n"
        except Exception as exc:
            yield f"data: {json.dumps({'type': 'error', 'error': str(exc)})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


# ── POST /demo/generate-test-scripts/stream ────────────────────────────────────

@router.post("/generate-test-scripts/stream")
async def generate_test_scripts_stream(
    container: AppContainer = Depends(get_container),
):
    """Stream Playwright test script generated by OpenAI in real time."""
    openai_client = container.get_openai_client()

    tc_summary = (
        "TC-001: Homepage Navigation (Positive, P0)\n"
        "TC-002: Search Bar Visibility (Positive, P0)\n"
        "TC-003: Navigation Bar Links (Positive, P1)\n"
        "TC-004: Search for 'wireless mouse' (Positive, P0)\n"
        "TC-005: Search Results Count > 5 (Positive, P1)\n"
        "TC-006: Product Card Title (Positive, P1)\n"
        "TC-007: Product Card Price (Positive, P1)\n"
        "TC-008: Product Card Rating Stars (Positive, P2)\n"
        "TC-009: Voice Search Button (Negative, P2) — expected FAIL\n"
        "TC-010: Sort by Price Low to High (Positive, P1)\n"
        "TC-011: Search for 'usb keyboard' (Positive, P0)\n"
        "TC-012: Second Search Relevance (Positive, P1)\n"
        "TC-013: Navigate to Cart Page (Positive, P0)\n"
        "TC-014: Try Before You Buy (Negative, P2) — expected FAIL\n"
        "TC-015: Search for 'laptop stand' (Positive, P1)\n"
        "TC-016: Product Image Thumbnails (Positive, P1)\n"
    )
    prompt = _SCRIPT_PROMPT.format(test_cases_summary=tc_summary)

    async def event_stream():
        full_text: list[str] = []
        try:
            async for token in openai_client.generate_stream(
                prompt=prompt,
                system=_SCRIPT_SYSTEM,
                temperature=0.2,
            ):
                full_text.append(token)
                yield f"data: {json.dumps({'type': 'token', 'token': token})}\n\n"
            yield f"data: {json.dumps({'type': 'done', 'text': ''.join(full_text)})}\n\n"
        except Exception as exc:
            yield f"data: {json.dumps({'type': 'error', 'error': str(exc)})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


# ── GET /demo/script ───────────────────────────────────────────────────────────

@router.get("/script")
async def get_demo_script():
    """Return the full demo Playwright script (for the Load Demo Script button)."""
    return {"script": DEMO_SCRIPT_TEXT}


# ── POST /demo/execute/stream ─────────────────────────────────────────────────

@router.post("/execute/stream")
async def execute_demo_stream():
    """
    Launch Playwright, run 16 Amazon test cases, and stream results via SSE.
    14 tests pass, 2 intentionally fail (with failure screenshots).
    Browser opens visibly with slowMo=1000.
    """

    async def event_stream():
        queue: asyncio.Queue = asyncio.Queue()
        task = asyncio.create_task(_execute_demo_tests(queue))

        while True:
            event = await queue.get()
            if event is None:
                break
            yield f"data: {json.dumps(event)}\n\n"

        try:
            await task
        except Exception as exc:
            yield f"data: {json.dumps({'type': 'error', 'error': str(exc)})}\n\n"

        yield f"data: {json.dumps({'type': 'stream-end'})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


# ── Playwright execution ──────────────────────────────────────────────────────

async def _execute_demo_tests(queue: asyncio.Queue):
    """Run 16 Amazon test cases with a visible Chromium browser."""
    from playwright.async_api import async_playwright

    await queue.put({"type": "status", "message": "Launching Chromium browser..."})

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False, slow_mo=1000)
        context = await browser.new_context(
            viewport={"width": 1280, "height": 800},
            locale="en-US",
            extra_http_headers={"Accept-Language": "en-US,en;q=0.9"},
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()
        page.set_default_timeout(12000)

        await queue.put({"type": "status", "message": "Browser launched. Running 16 test cases..."})

        test_cases = [
            ("TC-001", "Homepage Navigation", _tc_001_homepage),
            ("TC-002", "Search Bar Visibility", _tc_002_search_bar),
            ("TC-003", "Navigation Bar Links", _tc_003_nav_links),
            ("TC-004", "Search — Wireless Mouse", _tc_004_search_mouse),
            ("TC-005", "Search Results Count", _tc_005_results_count),
            ("TC-006", "Product Card Title", _tc_006_card_title),
            ("TC-007", "Product Card Price", _tc_007_card_price),
            ("TC-008", "Product Card Rating Stars", _tc_008_card_rating),
            ("TC-009", "Voice Search Button", _tc_009_voice_search),
            ("TC-010", "Sort by Price Low to High", _tc_010_sort_price),
            ("TC-011", "Search — USB Keyboard", _tc_011_search_keyboard),
            ("TC-012", "Second Search Relevance", _tc_012_search_relevance),
            ("TC-013", "Navigate to Cart Page", _tc_013_cart_page),
            ("TC-014", "Try Before You Buy", _tc_014_try_before_buy),
            ("TC-015", "Search — Laptop Stand", _tc_015_search_stand),
            ("TC-016", "Product Image Thumbnails", _tc_016_image_thumbs),
        ]

        passed = 0
        failed = 0

        for tc_id, tc_name, tc_fn in test_cases:
            await queue.put({
                "type": "test-start",
                "testId": tc_id,
                "name": tc_name,
            })
            try:
                await tc_fn(page)
                passed += 1
                await queue.put({
                    "type": "test-result",
                    "testId": tc_id,
                    "name": tc_name,
                    "status": "passed",
                })
            except Exception as e:
                failed += 1
                screenshot_b64 = ""
                try:
                    raw = await page.screenshot(full_page=False)
                    screenshot_b64 = base64.b64encode(raw).decode("utf-8")
                except Exception:
                    pass
                await queue.put({
                    "type": "test-result",
                    "testId": tc_id,
                    "name": tc_name,
                    "status": "failed",
                    "error": str(e),
                    "screenshot": screenshot_b64,
                })

        await queue.put({
            "type": "summary",
            "total": len(test_cases),
            "passed": passed,
            "failed": failed,
        })

        await browser.close()
        await queue.put({"type": "status", "message": "Browser closed. Execution complete."})

    await queue.put(None)  # Signal end


# ── Individual test case functions ─────────────────────────────────────────────

async def _tc_001_homepage(page):
    await page.goto("https://www.amazon.com/?language=en_US", wait_until="domcontentloaded")
    await page.wait_for_timeout(3000)
    title = await page.title()
    assert "amazon" in title.lower(), f"Expected 'Amazon' in title, got: {title}"


async def _tc_002_search_bar(page):
    search_box = page.locator("#twotabsearchtextbox")
    await search_box.wait_for(state="visible", timeout=5000)
    assert await search_box.is_enabled(), "Search bar is not enabled"


async def _tc_003_nav_links(page):
    logo = page.locator("#nav-logo-sprites")
    await logo.wait_for(state="visible", timeout=5000)
    cart = page.locator("#nav-cart")
    await cart.wait_for(state="visible", timeout=3000)


async def _tc_004_search_mouse(page):
    await page.fill("#twotabsearchtextbox", "wireless mouse")
    await page.click("#nav-search-submit-button")
    await page.wait_for_load_state("domcontentloaded")
    await page.wait_for_selector(
        "[data-component-type='s-search-result']", timeout=10000
    )


async def _tc_005_results_count(page):
    items = page.locator("[data-component-type='s-search-result']")
    count = await items.count()
    assert count > 5, f"Expected results > 5, got {count}"


async def _tc_006_card_title(page):
    first = page.locator("[data-component-type='s-search-result']").first
    title_el = first.locator("h2")
    await title_el.wait_for(state="visible", timeout=5000)
    title_text = (await title_el.inner_text()).strip()
    assert len(title_text) > 0, "Product title is empty"


async def _tc_007_card_price(page):
    first = page.locator("[data-component-type='s-search-result']").first
    price_whole = first.locator(".a-price-whole").first
    await price_whole.wait_for(state="visible", timeout=5000)
    price_text = (await price_whole.inner_text()).strip()
    assert len(price_text) > 0, "Price is empty"


async def _tc_008_card_rating(page):
    first = page.locator("[data-component-type='s-search-result']").first
    rating = first.locator(
        "[data-cy='reviews-ratings-slot'], .a-icon-star-small, "
        "[aria-label*='out of 5 stars']"
    ).first
    await rating.wait_for(state="visible", timeout=5000)


async def _tc_009_voice_search(page):
    """Intentionally fails — voice search not available on desktop web."""
    mic_btn = page.locator(
        "#nav-search-submit-button ~ [aria-label*='voice'], "
        ".nav-mic-button, #voice-search-button"
    )
    await mic_btn.wait_for(state="visible", timeout=3000)
    assert await mic_btn.is_visible(), "Voice search button not found"


async def _tc_010_sort_price(page):
    sort_dropdown = page.locator(
        "#s-result-sort-select, [aria-label='Sort by:']"
    ).first
    await sort_dropdown.wait_for(state="visible", timeout=5000)
    await page.select_option("#s-result-sort-select", "price-asc-rank")
    await page.wait_for_load_state("domcontentloaded")
    await page.wait_for_selector(
        "[data-component-type='s-search-result']", timeout=10000
    )


async def _tc_011_search_keyboard(page):
    await page.goto("https://www.amazon.com", wait_until="domcontentloaded")
    await page.fill("#twotabsearchtextbox", "usb keyboard")
    await page.click("#nav-search-submit-button")
    await page.wait_for_load_state("domcontentloaded")
    await page.wait_for_selector(
        "[data-component-type='s-search-result']", timeout=10000
    )


async def _tc_012_search_relevance(page):
    first = page.locator("[data-component-type='s-search-result']").first
    title_text = (await first.locator("h2").inner_text()).strip().lower()
    assert "keyboard" in title_text or "usb" in title_text, (
        f"Result not relevant: {title_text[:80]}"
    )


async def _tc_013_cart_page(page):
    await page.click("#nav-cart")
    await page.wait_for_load_state("domcontentloaded")
    assert "cart" in page.url.lower() or "gp/cart" in page.url.lower(), (
        f"Not on cart page: {page.url}"
    )


async def _tc_014_try_before_buy(page):
    """Intentionally fails — Try Before You Buy is only for clothing."""
    await page.goto(
        "https://www.amazon.com/gp/cart/view.html", wait_until="domcontentloaded"
    )
    tbb = page.get_by_text("Try Before You Buy")
    await tbb.first.wait_for(state="visible", timeout=3000)


async def _tc_015_search_stand(page):
    await page.goto("https://www.amazon.com", wait_until="domcontentloaded")
    await page.fill("#twotabsearchtextbox", "laptop stand")
    await page.click("#nav-search-submit-button")
    await page.wait_for_load_state("domcontentloaded")
    await page.wait_for_selector(
        "[data-component-type='s-search-result']", timeout=10000
    )


async def _tc_016_image_thumbs(page):
    first = page.locator("[data-component-type='s-search-result']").first
    img = first.locator("img.s-image").first
    await img.wait_for(state="visible", timeout=5000)
    src = await img.get_attribute("src")
    assert src and len(src) > 10, f"Image src is invalid: {src}"
