"""
Pydantic Data Models — Normalized Internal Schema
===================================================
These models define the single source of truth for backlog data
throughout the entire system. Regardless of what the raw API returns,
everything is normalized to these structures before being used.
"""

from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


# ── Status Enums ─────────────────────────────────────────────────────────────

class StoryStatus(str, Enum):
    PENDING     = "pending"       # No test cases generated yet
    GENERATING  = "generating"    # SLM is currently generating
    GENERATED   = "generated"     # Test cases created, not yet run
    RUNNING     = "running"       # Playwright is executing
    PASSED      = "passed"        # All tests passed
    FAILED      = "failed"        # One or more tests failed
    ERROR       = "error"         # Generation or execution error


# ── Core Backlog Models ───────────────────────────────────────────────────────

class AcceptanceCriterion(BaseModel):
    """A single acceptance criterion for a user story."""
    id: str
    text: str
    original_text: str = Field(
        description="The raw text as it came from the API, before any cleaning."
    )


class UserStory(BaseModel):
    """A single user story with its acceptance criteria."""
    id: str
    title: str
    description: str = ""
    acceptance_criteria: list[AcceptanceCriterion] = []
    status: StoryStatus = StoryStatus.PENDING


class Feature(BaseModel):
    """A feature grouping one or more user stories."""
    id: str
    title: str
    description: str = ""
    user_stories: list[UserStory] = []


class Epic(BaseModel):
    """Top-level epic grouping one or more features."""
    id: str
    title: str
    description: str = ""
    features: list[Feature] = []


class BacklogData(BaseModel):
    """
    The complete normalized backlog dataset.
    This is what gets cached and served to the frontend.
    """
    epics: list[Epic] = []
    total_stories: int = 0
    total_criteria: int = 0

    def compute_totals(self) -> None:
        """Recalculate summary counts after loading."""
        stories = 0
        criteria = 0
        for epic in self.epics:
            for feature in epic.features:
                stories += len(feature.user_stories)
                for story in feature.user_stories:
                    criteria += len(story.acceptance_criteria)
        self.total_stories = stories
        self.total_criteria = criteria


# ── Test Case Models ──────────────────────────────────────────────────────────

class TestStep(BaseModel):
    """A single step within a test case."""
    number: int
    action: str


class TestCase(BaseModel):
    """A structured test case generated by the SLM."""
    id: str                                  # e.g. TC001
    title: str
    criterion_id: str                        # which AC this was generated from
    story_id: str                            # parent user story
    preconditions: list[str] = []
    steps: list[TestStep] = []
    expected_result: str = ""
    test_type: str = "functional"            # functional | negative | edge


class GeneratedTestSuite(BaseModel):
    """All test cases generated for one user story."""
    model_config = {"protected_namespaces": ()}

    story_id: str
    story_title: str
    feature_title: Optional[str] = None
    epic_title: Optional[str] = None
    model_used: Optional[str] = None
    test_cases: list[TestCase] = []


# ── Playwright Models ─────────────────────────────────────────────────────────

class PlaywrightTestStatus(str, Enum):
    PENDING  = "pending"
    RUNNING  = "running"
    PASSED   = "passed"
    FAILED   = "failed"
    SKIPPED  = "skipped"


class PlaywrightTestResult(BaseModel):
    """Result of a single Playwright test execution."""
    test_case_id: str
    title: str
    status: PlaywrightTestStatus = PlaywrightTestStatus.PENDING
    duration_ms: Optional[int] = None
    error_message: Optional[str] = None
    failure_category: Optional[str] = None
    retry_recommended: Optional[bool] = None
    screenshot_path: Optional[str] = None     # URL like /artifacts/{run_id}/fn.png
    dom_snapshot_path: Optional[str] = None   # URL like /artifacts/{run_id}/fn.html
    console_errors: list[str] = []


class ExecutionSummary(BaseModel):
    """Summary of a full Playwright test run."""
    run_id: str = ""
    story_id: str
    total: int = 0
    passed: int = 0
    failed: int = 0
    skipped: int = 0
    duration_ms: Optional[int] = None
    video_path: Optional[str] = None          # URL like /artifacts/{run_id}/video.webm
    timestamp: Optional[str] = None
    results: list[PlaywrightTestResult] = []
